---
# ===================================================================
# ANSIBLE SERVICE ACCOUNT VERIFICATION PLAYBOOK
# ===================================================================
# 
# PURPOSE: Verify that the ansible service account is working correctly
# RUN AFTER: bootstrap-ansible-service-account.yml completes successfully
# ===================================================================

- name: Verify Ansible Service Account Configuration
  hosts: all_in_one
  become: true
  gather_facts: true
  
  tasks:
    
    # ===============================================================
    # BASIC CONNECTIVITY AND USER VERIFICATION
    # ===============================================================
    
    - name: Test ansible user exists and can connect
      ansible.builtin.shell: whoami
      register: current_user
      
    - name: Test ansible user can sudo without password
      ansible.builtin.shell: sudo whoami
      register: sudo_user
      
    - name: Test ansible user home directory exists
      ansible.builtin.stat:
        path: /home/ansible
      register: home_check
      
    # ===============================================================
    # SSH AND AUTOMATION VERIFICATION
    # ===============================================================
    
    - name: Test SSH key is properly installed
      ansible.builtin.stat:
        path: /home/ansible/.ssh/authorized_keys
      register: ssh_keys
      
    - name: Test sudoers file exists
      ansible.builtin.stat:
        path: /etc/sudoers.d/ansible
      register: sudoers_file
      
    # ===============================================================
    # AUTOMATION CAPABILITIES TEST
    # ===============================================================
    
    - name: Test package management capabilities
      ansible.builtin.package:
        name: curl
        state: present
      register: package_test
      
    - name: Test service status checking
      ansible.builtin.shell: systemctl is-active ssh || systemctl is-active sshd
      register: service_test
      failed_when: false
      
    - name: Test file operations
      ansible.builtin.copy:
        content: "Ansible automation test file"
        dest: /tmp/ansible-test-{{ ansible_date_time.epoch }}
        mode: '0644'
      register: file_test
      
    # ===============================================================
    # COMPREHENSIVE VERIFICATION REPORT
    # ===============================================================
    
    - name: Generate verification report
      ansible.builtin.debug:
        msg: |
          ========================================
          🔍 ANSIBLE SERVICE ACCOUNT VERIFICATION
          ========================================
          
          📋 SYSTEM INFO:
          • Hostname: {{ ansible_hostname }}
          • IP: {{ ansible_default_ipv4.address }}
          • OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          
          👤 USER VERIFICATION:
          • Current User: {{ current_user.stdout }}
          • Sudo Access: {{ sudo_user.stdout }}
          • Home Directory: {{ 'EXISTS ✅' if home_check.stat.exists else 'MISSING ❌' }}
          
          🔑 SSH CONFIGURATION:
          • SSH Keys: {{ 'CONFIGURED ✅' if ssh_keys.stat.exists else 'MISSING ❌' }}
          • Sudoers File: {{ 'EXISTS ✅' if sudoers_file.stat.exists else 'MISSING ❌' }}
          
          🔧 AUTOMATION CAPABILITIES:
          • Package Management: {{ 'WORKING ✅' if package_test is succeeded else 'FAILED ❌' }}
          • Service Checking: {{ 'WORKING ✅' if service_test.rc == 0 else 'NEEDS CHECK ⚠️' }}
          • File Operations: {{ 'WORKING ✅' if file_test is succeeded else 'FAILED ❌' }}
          
          ========================================
          {{ '🎉 ALL SYSTEMS OPERATIONAL - AUTOMATION READY!' if (current_user.stdout == 'ansible' and sudo_user.stdout == 'root' and ssh_keys.stat.exists) else '⚠️ SOME ISSUES DETECTED - CHECK ABOVE' }}
          ========================================

  # Clean up test files
  post_tasks:
    - name: Clean up test files
      ansible.builtin.file:
        path: /tmp/ansible-test-{{ ansible_date_time.epoch }}
        state: absent

# ===================================================================
# END OF VERIFICATION PLAYBOOK
# ===================================================================
